#!/usr/bin/env bash

set -euo pipefail

info() { printf '  -> %s\n' "$*"; }
ok() { printf '  OK %s\n' "$*"; }
warn() { printf '  !! %s\n' "$*"; }
fail() { printf '\n  ERROR %s\n\n' "$*" >&2; exit 1; }
step() { printf '\n-- Step %s/6 - %s\n' "$1" "$2"; }

random_hex() {
  local bytes="$1"
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex "$bytes"
  else
    od -An -N "$bytes" -tx1 /dev/urandom | tr -d ' \n'
  fi
}

read_env_value() {
  local file="$1" name="$2"
  [[ -f "$file" ]] || return 0
  grep -E "^${name}=" "$file" | tail -n 1 | cut -d'=' -f2- || true
}

echo
echo "  BOTNET"
echo "  Docker one-command installer"

step 1 "Checking dependencies"
command -v docker >/dev/null 2>&1 || fail "Docker CLI not found. Install Docker Desktop and retry."
docker info >/dev/null 2>&1 || fail "Docker daemon is not running. Start Docker Desktop and retry."
command -v npx >/dev/null 2>&1 || fail "npx not found. Install Node.js 20 or newer and retry."
command -v curl >/dev/null 2>&1 || fail "curl not found. Install curl and retry."
ok "Docker, Node.js, npm, and curl are available"

step 2 "Starting local Supabase"
if npx --yes supabase status >/dev/null 2>&1; then
  ok "Local Supabase is already running"
else
  info "Starting Supabase; the first run can take a few minutes"
  npx --yes supabase start || fail "Supabase failed to start."
fi

STATUS_OUTPUT=$(npx --yes supabase status)
ANON_KEY=$(printf '%s\n' "$STATUS_OUTPUT" | grep -Eo 'sb_publishable_[^[:space:]]+' | head -n 1 || true)
SERVICE_ROLE_KEY=$(printf '%s\n' "$STATUS_OUTPUT" | grep -Eo 'sb_secret_[^[:space:]]+' | head -n 1 || true)
[[ -n "$ANON_KEY" ]] || ANON_KEY=$(printf '%s\n' "$STATUS_OUTPUT" | grep -i 'anon key:' | awk '{print $NF}' | head -n 1 || true)
[[ -n "$SERVICE_ROLE_KEY" ]] || SERVICE_ROLE_KEY=$(printf '%s\n' "$STATUS_OUTPUT" | grep -i 'service_role key:' | awk '{print $NF}' | head -n 1 || true)
SUPABASE_URL=$(printf '%s\n' "$STATUS_OUTPUT" | grep -i 'API URL:' | awk '{print $NF}' | head -n 1 || true)
STUDIO_URL=$(printf '%s\n' "$STATUS_OUTPUT" | grep -i 'Studio URL:' | awk '{print $NF}' | head -n 1 || true)

[[ -n "$ANON_KEY" ]] || fail "Could not parse the publishable key from Supabase status."
[[ -n "$SERVICE_ROLE_KEY" ]] || fail "Could not parse the service-role key from Supabase status."
[[ -n "$SUPABASE_URL" ]] || fail "Could not parse the API URL from Supabase status."

SUPABASE_INTERNAL_URL=$(printf '%s\n' "$SUPABASE_URL" | sed -E 's#^(https?://)(127\.0\.0\.1|localhost)#\1host.docker.internal#')
ok "Supabase credentials detected"
info "Applying pending local database migrations"
npx --yes supabase migration up --local || fail "Could not apply local Supabase migrations."
ok "Local database migrations are current"

step 3 "Resolving application secrets"
ENCRYPTION_KEY=$(read_env_value .env.local ENCRYPTION_KEY)
[[ -n "$ENCRYPTION_KEY" ]] || ENCRYPTION_KEY=$(read_env_value .env.docker ENCRYPTION_KEY)
SETUP_SECRET=$(read_env_value .env.local SETUP_SECRET)
[[ -n "$SETUP_SECRET" ]] || SETUP_SECRET=$(read_env_value .env.docker SETUP_SECRET)

if [[ -z "$ENCRYPTION_KEY" ]]; then
  ENCRYPTION_KEY=$(random_hex 32)
  ok "Generated ENCRYPTION_KEY"
else
  ok "Reusing ENCRYPTION_KEY"
fi

if [[ -z "$SETUP_SECRET" ]]; then
  SETUP_SECRET=$(random_hex 24)
  ok "Generated SETUP_SECRET"
else
  ok "Reusing SETUP_SECRET"
fi

step 4 "Writing .env.docker"
cat > .env.docker <<EOF
# Auto-generated by docker-setup.sh. Do not commit this file.
NEXT_PUBLIC_SUPABASE_URL=$SUPABASE_URL
SUPABASE_INTERNAL_URL=$SUPABASE_INTERNAL_URL
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=$ANON_KEY
SUPABASE_SECRET_KEY=$SERVICE_ROLE_KEY
SETUP_SECRET=$SETUP_SECRET
ENCRYPTION_KEY=$ENCRYPTION_KEY
INNGEST_DEV=1
EOF
ok ".env.docker is ready"

step 5 "Launching Docker Compose"
docker compose --env-file .env.docker up --build -d || fail "Docker Compose failed to start."

step 6 "Waiting for the application"
READY=0
for _ in $(seq 1 30); do
  if curl --fail --silent --max-time 3 http://localhost:3000/api/setup/admin >/dev/null; then
    READY=1
    break
  fi
  sleep 2
done
[[ "$READY" -eq 1 ]] || fail "The app did not become ready. Run: docker compose --env-file .env.docker logs"

echo
echo "BotNet is ready."
echo "App:      http://localhost:3000"
echo "Setup:    http://localhost:3000/setup?token=$SETUP_SECRET"
echo "Inngest:  http://localhost:8288"
[[ -n "$STUDIO_URL" ]] && echo "Supabase: $STUDIO_URL"
echo
echo "Logs: docker compose --env-file .env.docker logs -f"
echo "Stop: docker compose --env-file .env.docker down"
